import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://mssit2.lntsufin.com/');
  await page.getByRole('button', { name: 'track order Login' }).click();
  await page.getByRole('spinbutton').fill('44444444444');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.getByRole('dialog').locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('textbox', { name: 'Enter product name here...' }).click();
  await page.locator('div').filter({ hasText: /^Audio Cables$/ }).nth(1).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('Rakesh AUX Aux Cable Carbon Fibre 1.8 mtr Audio Cables 4.7 17 Ratings 600+').click();
  const page1 = await page1Promise;
  await page1.getByText('51+').click();
  await page1.locator('.input-group-append > .input-group-text').click();
  await page1.locator('.input-group-append > .input-group-text').click();
  await page1.locator('.input-group-append > .input-group-text').click();
  await page1.locator('.input-group-append > .input-group-text').click();
  await page1.locator('#pdp-rfq-button').click();
  await page1.goto('https://mssit2.lntsufin.com/buyer/#/request-quote/rfq-select-product?skuId=16249-1&pincode=412111&quantity=55.0&fromTrend=n');
  await page1.locator('#fileUploads').click();
  await page1.locator('#fileUploads').setInputFiles('product_order_PSS04577-0029.pdf');
  await page1.getByRole('button', { name: 'Proceed' }).click();
  await page1.getByRole('button', { name: 'Submit Request' }).click();
  await page1.getByRole('button', { name: 'Close' }).click();
  await page1.locator('.rfq-status-box').click();
  await page1.getByRole('button', { name: 'Track your RFQ' }).click();
  await page1.getByRole('button', { name: 'View RFQ Details' }).first().click();
  await page1.getByText('No Quotation Received').click();
  await page1.locator('a').filter({ hasText: 'RFQ ID # RSS041244-0023' }).click();
  await page1.getByRole('button', { name: 'RFQ Terms' }).click();
  await page1.getByRole('img', { name: 'close icon' }).nth(3).click();
  await page1.goto('https://mssit2.lntsufin.com/seller');
  await page1.getByRole('button', { name: 'Login' }).click();
  await page1.getByRole('button', { name: 'RFQs icon active RFQs' }).click();
  await page1.getByRole('button', { name: 'View Details' }).first().click();
  await page1.getByText('Quantity *Piece(s)').click();
  await page1.getByText('Delivered Price *₹/ Per Piece').click();
  await page1.getByRole('spinbutton').fill('1000');
  await page1.getByText('GST *%').click();
  await page1.locator('#collapse0 input[type="text"]').fill('10');
  await page1.locator('div').filter({ hasText: /^Price Validity$/ }).nth(1).click();
  await page1.locator('base-datepicker svg').click();
  await page1.getByText('20', { exact: true }).click();
  await page1.getByText('Time required to deliver').click();
  await page1.getByRole('button').nth(3).click();
  await page1.getByRole('button').nth(3).click();
  await page1.getByRole('button').nth(3).click();
  await page1.getByRole('button').nth(3).click();
  await page1.getByRole('button').nth(3).click();
  await page1.locator('div').filter({ hasText: /^\+ Add Ex-works Price$/ }).nth(1).click();
  await page1.getByText('Quantity Piece(s)').click();
  await page1.getByText('Ex-works Price ₹/ Per Piece(s)').click();
  await page1.getByRole('spinbutton').nth(1).fill('1020');
  await page1.getByText('GST %').click();
  await page1.locator('input[type="text"]').nth(1).fill('9');
  await page1.locator('div').filter({ hasText: /^Price Validity$/ }).nth(3).click();
  await page1.getByText('Time required to keep').click();
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page1.getByText('+ Upload Documents').click();
  await page1.getByRole('button', { name: 'Choose File' }).click();
  await page1.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04577-0029.pdf');
  await page1.getByRole('button', { name: 'Yes' }).click();
  await page1.getByRole('button', { name: 'Submit Quote' }).click();
  await page1.getByRole('button', { name: 'Ok' }).click();
  await page1.getByRole('button', { name: 'Close' }).click();
  await page1.goto('https://mssit2.lntsufin.com/buyer/#/category-preference');
  await page1.getByTitle('Request Quote for Bulk', { exact: true }).click();
  await page1.getByTitle('Request Quote for Bulk', { exact: true }).click();
  await page1.getByTitle('Request Quote for Bulk', { exact: true }).click();
  await page1.getByTitle('Request Quote for Bulk', { exact: true }).click();
  await page1.getByTitle('Request Quote for Bulk', { exact: true }).click();
  await page1.getByTitle('Request Quote for Bulk', { exact: true }).click();
  await page1.goto('https://mssit2.lntsufin.com/buyer/#/category-preference');
  await page1.locator('#searchid').click();
  await page1.locator('#searchid').fill('audio cables');
  await page1.locator('#searchid').press('Enter');
  await page1.getByRole('button', { name: 'Proceed' }).click();
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page1.getByRole('button').filter({ hasText: /^$/ }).nth(3).click();
  await page1.getByText('Terms of RFQ Edit Delivery').first().click();
  await page1.locator('.attached-document-box > .heading-box').first().click();
  await page1.getByRole('button', { name: 'Choose File' }).nth(1).click();
  await page1.getByRole('button', { name: 'Choose File' }).nth(1).setInputFiles('product_order_PSS04577-0029.pdf');
  await page1.locator('div:nth-child(3) > .order-prod-tile > .order-prod-block > div > div > .order-prod-left-section > .order-prod-desp-box > .order-prod-desp > .order-quantity-sec > .row > .col-7 > .input-group-append > .input-group-text').click();
  await page1.locator('div:nth-child(3) > .order-prod-tile > .order-prod-block > div > div:nth-child(3) > .order-prod-right-section > .attached-document-box > .heading-box').click();
  await page1.getByRole('button', { name: 'Choose File' }).nth(2).click();
  await page1.getByRole('button', { name: 'Choose File' }).nth(2).setInputFiles('product_order_PSS04577-0029.pdf');
  await page1.getByRole('button', { name: 'Proceed' }).click();
  await page1.getByText('Preferences for shortlisting seller Seller Location + Add LocationPan India You').click();
  await page1.getByRole('button', { name: 'Submit Request' }).click();
  await page1.getByRole('button', { name: 'Close' }).click();
});