import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://mssit2.lntsufin.com/');
  await page.getByRole('button', { name: 'track order Login' }).click();
  await page.getByRole('spinbutton').fill('44444444444');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.getByRole('dialog').locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.goto('https://mssit2.lntsufin.com/buyer/#/buyer-feedback-seller/OI3189-0000002?title=Please%20share%20your%20valuable%20feedback&entityName=ORDER&entityId=PSS04573-0014&questionSetType=BUYER_ORDER_SELLER&redirectUrl=%2Fhome&sellerName=Rakesh%20SIT%20Four%20Seller&lineItems=Safety%20Jackets%20%2B%201%20other%20Products&providerOrgId=OI3189-0000004&rfqReferenceId=');
  await page.getByRole('textbox', { name: 'Enter product name here...' }).click();
  await page.locator('div').filter({ hasText: /^Audio Cables$/ }).nth(1).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('Rakesh AUX Aux Cable Carbon Fibre 1.8 mtr Audio Cables 4.7 17 Ratings 600+').click();
  const page1 = await page1Promise;
  await page1.locator('.input-group-append > .input-group-text').click();
  await page1.getByRole('button', { name: 'Add To Cart' }).click();
  await page1.getByRole('button', { name: 'Buy Now' }).click();
  await page1.goto('https://mssit2.lntsufin.com/buyer/#/cart/stp-checkout?shipping=true&cartId=CSS04727-0039&pincode=412111');
  await page1.getByText('Billing address same as').click();
  await page1.getByText('Billing address same as').click();
  await page1.getByText('Product Price ₹ 180.00 Product GST ₹ 18.00 Shipping Price ₹ 75.00 Shipping GST').nth(1).click();
  await page1.getByRole('button', { name: 'Pay ₹' }).click();
  await page1.locator('#paymentStatus').selectOption('Success');
  await page1.getByRole('button', { name: 'Pay' }).click();
  await page1.getByRole('button', { name: 'OK' }).click();
  await page1.getByRole('button', { name: 'Order details' }).click();
  await page1.getByRole('button', { name: 'View Details' }).first().click();
  await page1.getByText('Order ID # PSS04577-0036 Placed on 16 Jan,').click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByText('Seller Name Rakesh SIT Four').click();
  const page2 = await page2Promise;
  await page1.getByText('Payment Terms Advance').click();
  await page1.getByText('Delivery Mode Shipped by L&T-').click();
  await page1.getByText('Track Shipment').click();
  await page1.locator('div').filter({ hasText: /^Shipment Initiated 16 Jan, 2026$/ }).nth(1).click();
  await page1.getByRole('img', { name: 'close icon' }).nth(1).click();
  await page1.goto('https://mssit2.lntsufin.com/dashboard/#/seller/dashboard');
  await page1.getByRole('button', { name: 'Login' }).click();
  await page1.locator('#mobileLoginNumber').fill('1063123506');
  await page1.getByRole('button', { name: 'Get OTP' }).click();
  await page1.locator('#otpInput').fill('1234');
  await page1.getByRole('button', { name: 'Verify' }).click();
  await page1.getByRole('button', { name: 'Orders icon active Orders' }).click();
  await page1.getByRole('button', { name: 'Active (439)' }).click();
  await page1.getByRole('heading', { name: 'Rakesh AUX Aux Cable Carbon' }).first().click();
  await page1.getByText('Quantity 2 Piece(s)').nth(1).click();
  await page1.getByText('Item Value₹').nth(1).click();
  await page1.getByRole('button', { name: 'View Details' }).first().click();
  await page1.getByText('Ship To: Buyer One mssit4CopyBuyer Onemssitfour, Bcg, Pune, MAHARASHTRA 412111').click();
  await page1.getByText('Pickup From: Rakesh SIT Four SellerNew Business Area SellerElectronic Zone').first().click();
  await page1.locator('.order-info-row').first().click();
  await page1.getByText('Delivery Mode Shipped by L&T-').click();
  await page1.getByText('Buyer\'s Payment Terms Paid 100% On Order Placement').click();
  await page1.getByText('Bill To: Buyer One mssit4Buyer Onemssitfour, Bcg, Pune, MAHARASHTRA 412111').click();
  await page1.getByRole('heading', { name: 'Payment Summary' }).click();
  await page1.getByRole('button', { name: 'Prepare for Dispatch' }).click();
  await page1.getByRole('heading', { name: 'Upload Documents' }).click();
  await page1.getByText('Invoice Amount: ₹').click();
  await page1.getByText('Invoice* Upload').click();
  await page1.getByRole('button', { name: 'Upload' }).first().click();
  await page1.getByRole('textbox', { name: 'Invoice Number *' }).click();
  await page1.getByRole('textbox', { name: 'Invoice Number *' }).fill('12345');
  await page1.getByRole('img').click();
  await page1.getByText('16', { exact: true }).click();
  await page1.getByRole('button', { name: 'Choose File' }).click();
  await page1.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04577-0029.pdf');
  await page1.getByRole('button', { name: 'Submit' }).click();
  await page1.getByRole('button', { name: 'Save & Next' }).click();
  await page1.getByRole('heading', { name: 'Packaging Details' }).click();
  await page1.getByText('+Add PackageDimension').click();
  await page1.getByRole('button', { name: 'Submit' }).click();
  await page1.getByText('Pickup Scheduled Successfully Pickup will be done within 2 days. Keep your').click();
  await page1.getByRole('button', { name: 'OK' }).click();
  await page1.getByText('Pickup scheduled date 17 Jan, 2026 Track Shipment Manage Documents').click();
  await page1.getByText('Track Shipment').click();
  await page1.getByRole('img', { name: 'close icon' }).nth(1).click();
  await page1.goto('https://mssit2.lntsufin.com/buyer/#/category-preference');
  await page1.getByRole('button', { name: 'track orderHi, Rakesh ' }).click();
  await page1.getByRole('button', { name: 'track orderHi, Rakesh' }).click();
});