import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://mssit3.lntsufin.com/shome');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('#mobileLoginNumber').fill('1063123506');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'Orders icon active Orders' }).click();
  await page.goto('https://mssit3.lntsufin.com/seller/#/productOrders/active-orders?title=Manage%20Product%20Orders');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).click();
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).fill('PSS04567-0007');
  await page.getByRole('button', { name: 'filters icon Filters' }).click();
  await page.getByText('Order Confirmed').click();
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).click();
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).fill('PSS04567-0007');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).fill('PSS04567-0007');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('Enter');
  await page.getByRole('button', { name: 'filters icon Filters' }).click();
  await page.getByText('Order Confirmed').click();
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('button', { name: 'View Details' }).nth(2).click();
  await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Prepare for Dispatch' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Upload' }).first().click();
  await page.getByRole('textbox', { name: 'Invoice Number *' }).click();
  await page.getByRole('textbox', { name: 'Invoice Number *' }).fill('111111');
  await page.getByRole('img').click();
  await page.getByText('6', { exact: true }).click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04717-0074.pdf');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByRole('img').nth(5).click();
  await page.getByText('6', { exact: true }).click();
  await page.locator('path').nth(2).click();
  await page.getByText('6', { exact: true }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByRole('button', { name: 'Select Billing Address' }).click();
  await page.locator('#selectAddress8628-10').check();
  await page.getByRole('button', { name: 'Confirm Address' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Is Shipment Dispatched?' }).click();
  await page.locator('#mat-input-11').click();
  await page.locator('#mat-input-11').click();
  await page.locator('.ng-star-inserted > .modal-dialog-centered > .modal-content > .modal-body > .update-details-section > .update-details-form > div > .col-12.col-lg-6.pl-0.pr-0.pr-lg-2 > .form-group > .dateFilter > base-datepicker > .input-group > .input-group-append > .input-group-text > .mat-datepicker-toggle-default-icon > path').click();
  await page.locator('#mat-dialog-3 #transporterName').click();
  await page.locator('#mat-dialog-3 #transporterName').fill('Seller');
  await page.locator('#mat-dialog-3 #trackingNumber').click();
  await page.locator('#mat-dialog-3 #trackingNumber').fill('3333');
  await page.locator('#mat-dialog-3 #trackingUrl').click();
  await page.locator('#mat-dialog-3 #trackingUrl').fill('www.google.com');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Is Shipment Delivered?' }).click();
  await page.getByRole('img').click();
  await page.getByText('6', { exact: true }).click();
  await page.getByRole('textbox', { name: 'Type here' }).click();
  await page.getByRole('textbox', { name: 'Type here' }).fill('11111');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04717-0074.pdf');
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByText('Track Shipment').click();
  await page.getByRole('img', { name: 'close icon' }).nth(1).click();
  await page.getByText('RSS041332-').click();
});