import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    test.setTimeout(0);
  await page.goto('https://mssit3.lntsufin.com/');
  await page.getByRole('button', { name: 'track order Login' }).click();
  await page.getByRole('spinbutton').fill('44444444444');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.getByRole('dialog').locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.waitForLoadState('networkidle');
  await page.goto('https://mssit3.lntsufin.com/buyer/#/buyer-feedback-seller/OI3189-0000002?title=Please%20share%20your%20valuable%20feedback&entityName=ORDER&entityId=PSS04509-0030&questionSetType=BUYER_ORDER_SELLER&redirectUrl=%2Fhome&sellerName=seller%20suraj&lineItems=mat1%20Hand%20Woven%20Bamboo%20Mat%204%20Ft%20X%203%20Ft&providerOrgId=OI3192-0000026&rfqReferenceId=');
  // await page.getByRole('button', { name: 'track orderHi, Buyer ' }).click();
  // await page.getByRole('button', { name: 'track orderHi, Buyer' }).click();
  await page.waitForLoadState('networkidle');
  await page.getByRole('button', { name: 'track order Hi, Buyer ' }).click();
  await page.getByRole('button', { name: 'track orderHi, Buyer' }).click();
  // await page.goto('https://mssit3.lntsufin.com/buyer/#/request-quote/manage/rfq-listing?title=Manage%20RFQs');
  // await page.getByRole('button', { name: 'View RFQ Details' }).first().click();
  await page.waitForLoadState('networkidle');
  await page.goto('https://mssit3.lntsufin.com/buyer/#/request-quote/manage/rfq-listing?title=Manage%20RFQs');
  await page.getByRole('button', { name: 'View RFQ Details' }).first().click();
  await page.getByRole('button', { name: 'Accept Quote' }).click();
  await page.getByRole('button', { name: 'Place Order' }).click();
  await page.getByRole('button', { name: 'Proceed to Payment' }).click();
  await page.getByRole('button', { name: 'Pay Now' }).click();
  await page.locator('#paymentStatus').selectOption('Success');
  await page.getByRole('button', { name: 'Pay' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  // await page.getByRole('button', { name: 'track orderHi, Buyer ' }).click();
  // await page.getByRole('button', { name: 'track orderHi, Buyer' }).click();
});