import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(0);
  await page.locator('body').click();
  await page.goto('https://mssit3.lntsufin.com/shome');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('#mobileLoginNumber').fill('1063123506');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.waitForTimeout(2000);
  await page.getByRole('button', { name: 'Orders icon active Orders' }).click();
  await page.goto('https://mssit3.lntsufin.com/seller/#/productOrders/active-orders?title=Manage%20Product%20Orders');
   await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).click();
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).fill('PSS04717-0009');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('Enter');
  await page.getByRole('button', { name: 'filters icon Filters' }).click();
  await page.getByText('Order Confirmed').click();
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  const revamp = page.locator('sufin-portals-logistics-sku-revamp');
  await expect(revamp).toBeVisible();
  await revamp.locator('input.allow-brand-input').first().check({ force: true });
//   await page.getByRole('checkbox').check();
  await page.getByRole('button', { name: 'Prepare for Dispatch' }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Upload' }).first().click();
  await page.getByRole('textbox', { name: 'Invoice Number *' }).click();
  await page.getByRole('textbox', { name: 'Invoice Number *' }).fill('12345');
  await page.getByRole('img').click();
  await page.getByText('2', { exact: true }).click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04577-0029.pdf');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Upload' }).click();
  await page.getByRole('textbox', { name: 'E-Way Bill Number *' }).click();
  await page.getByRole('textbox', { name: 'E-Way Bill Number *' }).fill('234');
  await page.locator('div').filter({ hasText: /^E-Way Bill Number \*$/ }).nth(1).click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04577-0029.pdf');
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.locator('path').nth(1).click();
  await page.getByText('2', { exact: true }).click();
  await page.locator('svg').nth(2).click();
  await page.getByText('2', { exact: true }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByRole('button', { name: 'Select Billing Address' }).click();
  await page.locator('#selectAddress8628-10').check();
  await page.getByRole('button', { name: 'Confirm Address' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
});