import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(0);
  await page.goto('https://mssit3.lntsufin.com/shome');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('#mobileLoginNumber').fill('1063123506');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'Orders icon active Orders' }).click();
  await page.goto('https://mssit3.lntsufin.com/seller/#/productOrders/active-orders?title=Manage%20Product%20Orders');
   await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).click();
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).fill('PSS04717-0009');
  //await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('Enter');
  await page.getByRole('button', { name: 'filters icon Filters' }).click();
  await page.getByText('Order Confirmed').click();
  await page.getByText('Last 3 Months').click();
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  const revamp = page.locator('sufin-portals-logistics-sku-revamp');
  await expect(revamp).toBeVisible();
  await revamp.locator('input.allow-brand-input').first().check({ force: true });
 // await page.getByRole('button', { name: 'Apply' }).click();
 // await page.getByRole('button', { name: 'View Details' }).first().click();
 // await page.getByRole('checkbox').nth(1).check();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('4');
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('Click Here').click();
  const page1 = await page1Promise;
  await page.getByText('Download Documents').click();
  const downloadPromise = page.waitForEvent('download');
  await page.locator('a').filter({ hasText: 'Order Summary' }).click();
  const download = await downloadPromise;
  await page.getByRole('img', { name: 'close icon' }).click();
  await page.locator('.cdk-overlay-backdrop').click();
  await page.getByRole('button', { name: 'Prepare for Dispatch' }).click();
  await page.getByText('L&T-SuFin Logistics', { exact: true }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Upload' }).first().click();
  await page.getByRole('textbox', { name: 'Invoice Number *' }).click();
  await page.getByRole('textbox', { name: 'Invoice Number *' }).fill('11');
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('img').click();
  await page.getByText('2', { exact: true }).click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04577-0029.pdf');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Upload' }).click();
  await page.getByRole('textbox', { name: 'E-Way Bill Number *' }).click();
  await page.getByRole('textbox', { name: 'E-Way Bill Number *' }).fill('222222');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04577-0029.pdf');
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.locator('path').nth(1).click();
  await page.getByText('2', { exact: true }).click();
  await page.locator('svg').nth(2).click();
  await page.getByText('4', { exact: true }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByText('+Add Package').click();
  await page.locator('#length_0').click();
  await page.locator('#length_0').fill('11');
  await page.locator('#width_0').click();
  await page.locator('#width_0').fill('12');
  await page.locator('#height0').click();
  await page.locator('#height0').fill('11');
  await page.locator('#weight0').click();
  await page.locator('#weight0').fill('11');
  await page.getByRole('cell').filter({ hasText: 'Number of Packs cannot be' }).getByRole('spinbutton').click();
  await page.getByRole('cell').filter({ hasText: 'Number of Packs cannot be' }).getByRole('spinbutton').fill('11');
  await page.getByText('+Add Package').click();
  await page.locator('#length_1').click();
  await page.locator('#length_1').fill('22');
  await page.locator('#width_1').click();
  await page.locator('#width_1').fill('111');
  await page.locator('#height1').click();
  await page.locator('#height1').fill('11');
  await page.locator('#weight1').click();
  await page.locator('#weight1').fill('111');
  await page.locator('#noOfPacks1').click();
  await page.locator('#noOfPacks1').fill('11');
  await page.locator('tr:nth-child(2) > .align-middle > .fa').click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByRole('button', { name: 'Select Billing Address' }).click();
  await page.locator('#selectAddress8628-10').check();
  await page.getByRole('button', { name: 'Confirm Address' }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByText('Pay From My Receivables').click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Download Documents').click();
  const download1Promise = page.waitForEvent('download');
  await page.locator('a').filter({ hasText: /^Invoice$/ }).click();
  const download1 = await download1Promise;
  const download2Promise = page.waitForEvent('download');
  await page.locator('a').filter({ hasText: 'E-Way Bill' }).click();
  const download2 = await download2Promise;
  await page.getByRole('img', { name: 'close icon' }).click();
  await page.locator('.cdk-overlay-backdrop').click();
  await page.getByRole('button', { name: 'Manage Documents' }).click();
  await page.getByRole('img', { name: 'close icon' }).nth(2).click();
  await page.getByText('Track Shipment').click();
  await page.getByRole('img', { name: 'close icon' }).nth(1).click();
  await page.locator('sufin-portals-logistics-sku-shipment').getByText('View Specifications').click();
  await page.locator('.view-specifications-close').first().click();
});