import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(0);
  await page.goto('https://mssit3.lntsufin.com/shome');
 // await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('#mobileLoginNumber').fill('1063123506');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'Orders icon active Orders' }).click();
  // await page.locator('seller-root').click();
  // await page.goto('https://mssit3.lntsufin.com/seller/#/productOrders/active-orders?title=Manage%20Product%20Orders');
  // await page.getByRole('button', { name: 'filters icon Filters' }).click();
  // await page.getByText('Order Confirmed').click();
  // await page.getByRole('button', { name: 'Apply' }).click();
  // await page.getByText('Order ID # PSS04717-0106').click();
    await page.waitForTimeout(500);

  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).click();
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).fill('PSS04717-0107');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('Enter');
      await page.waitForTimeout(500);

  await page.getByRole('button', { name: 'View Details' }).first().click();
    await page.waitForTimeout(500);

  await page.getByRole('button', { name: 'Prepare for Dispatch' }).first().click();
  await page.getByRole('button', { name: 'Upload' }).first().click();
  await page.getByRole('textbox', { name: 'Invoice Number *' }).click();
  await page.getByRole('textbox', { name: 'Invoice Number *' }).fill('555');
  await page.locator('#mat-dialog-0 path').click();
  await page.getByText('5', { exact: true }).click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04717-0074.pdf');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.locator('#length_0').click();
  await page.locator('#length_0').fill('1');
  await page.locator('#width_0').click();
  await page.locator('#width_0').click();
  await page.locator('#width_0').press('ArrowLeft');
  await page.locator('#width_0').press('ArrowLeft');
  await page.locator('#width_0').fill('1.00');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByRole('button', { name: 'Manage Documents' }).click();
  await page.getByRole('button', { name: 'Choose File' }).first().click();
  await page.getByRole('button', { name: 'Choose File' }).first().setInputFiles('product_order_PSS04717-0074.pdf');
  await page.goto('https://mssit3.lntsufin.com/seller/#/seller-logistics/product-order-details?productOrderId=PSS04717-0106');
  await page.getByText('Track Shipment').click();
  await page.getByRole('img', { name: 'close icon' }).nth(1).click();
  await page.getByText('Download Documents').click();
  const downloadPromise = page.waitForEvent('download');
  await page.locator('a').filter({ hasText: /^Invoice$/ }).click();
  const download = await downloadPromise;
  const download1Promise = page.waitForEvent('download');
  await page.locator('a').filter({ hasText: 'E-Way Bill' }).click();
  const download1 = await download1Promise;
  await page.getByRole('img', { name: 'close icon' }).click();
});