import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(0);
  await page.goto('https://mssit3.lntsufin.com/');
  await page.getByRole('button', { name: 'track order Login' }).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('44444444444');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.getByRole('dialog').locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.goto('https://mssit3.lntsufin.com/buyer/#/unauthorized');
  await page.getByRole('textbox', { name: 'Enter product name here...' }).click();
  await page.getByRole('textbox', { name: 'Enter product name here...' }).fill('audik');
  await page.locator('div').filter({ hasText: /^Audio Cables$/ }).nth(2).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('Rakesh AUX Aux Cable Carbon Fibre 1.8 mtr Audio Cables 2.0 4 Ratings 600+').click();
  const page1 = await page1Promise;
  await page1.getByText('51+').click();
  await page1.locator('#pdp-rfq-button').click();
  await page1.goto('https://mssit3.lntsufin.com/buyer/#/request-quote/rfq-select-product?skuId=16249-1&pincode=400001&quantity=51.0&fromTrend=n');
  await page1.getByRole('textbox').nth(1).click();
  await page1.getByRole('textbox').nth(1).fill('61');
  await page1.getByRole('checkbox', { name: 'Allow quotes from specific' }).check();
  await page1.locator('div').filter({ hasText: /^Rakesh$/ }).nth(1).click();
  await page1.locator('#gstin-dropdown-btn').click();
  await page1.getByRole('listitem').filter({ hasText: 'Rakesh' }).click();
  await page1.getByRole('button', { name: 'Edit' }).click();
  await page1.locator('textarea').click();
  await page1.locator('textarea').fill('Cable Length: 1.8 mtr\nCompatible Devices: All\nConnector: 3.5 mm\nMounting Hardware: Yes\nProduct Dimension: 762 x 0.99 x 0.99 (cm)\nCable Type: Aux Cable\nColour: Red\nMaterial: Carbon Fibre\nModel: AUX\nCreated By: Rakesh\nRemark: ');
  await page1.getByLabel('Select Products').getByRole('button', { name: 'Save' }).click();
  await page1.getByText('Terms of RFQ Edit').click();
  await page1.getByRole('link', { name: 'Edit' }).click();
  await page1.locator('path').click();
  await page1.getByText('7', { exact: true }).click();
  await page1.locator('input[type="text"]').nth(5).click();
  await page1.locator('input[type="text"]').nth(5).fill('400001');
  await page1.getByText('Pay on Order PlacementBank').click();
  await page1.getByRole('spinbutton').first().click();
  await page1.getByRole('spinbutton').first().fill('100');
  await page1.getByRole('spinbutton').nth(1).click();
  await page1.getByRole('spinbutton').nth(1).fill('0');
  await page1.getByRole('spinbutton').nth(2).click();
  await page1.getByRole('spinbutton').nth(2).fill('0');
  await page1.locator('#allowSpecificBrands1').nth(1).check();
  await page1.locator('#allowSpecificBrands1').nth(1).uncheck();
  await page1.getByRole('button', { name: 'Save' }).first().click();
  await page1.locator('#fileUploads').click();
  await page1.locator('#fileUploads').setInputFiles('product_order_PSS04577-0029.pdf');
  await page1.getByRole('button', { name: 'Add another variant of Audio' }).click();
  await page1.getByRole('button', { name: 'Delete Icon' }).first().click();
  await page1.getByRole('button', { name: 'Add More Products in the RFQ' }).click();
  await page1.getByRole('tabpanel', { name: 'Select Products' }).getByPlaceholder('Enter product name here...').click();
  await page1.getByRole('tabpanel', { name: 'Select Products' }).getByPlaceholder('Enter product name here...').fill('audio');
  await page1.getByLabel('Select Products').getByRole('listitem').filter({ hasText: 'Audio Cables' }).click();
  await page1.getByRole('textbox').nth(1).click();
  await page1.getByRole('textbox').nth(1).fill('10');
  await page1.getByRole('checkbox', { name: 'Allow quotes from specific' }).check();
  await page1.locator('#gstin-dropdown-btn').first().click();
  await page1.getByRole('checkbox', { name: 'Allow quotes from specific' }).uncheck();
  await page1.getByRole('button', { name: 'Edit' }).first().click();
  await page1.getByRole('textbox').nth(2).click();
  await page1.getByRole('textbox').nth(2).fill('Cable Length: \nCable Type: \nConnector: \nCompatible Devices: \nProduct Dimension: \nMounting Hardware: strong\nMaterial: \nModel: \nColour: \nRemark: ');
  await page1.getByRole('textbox').nth(2).click();
  await page1.getByRole('textbox').nth(2).click();
  await page1.getByLabel('Select Products').getByRole('button', { name: 'Save' }).click();
  await page1.getByText('Terms of RFQ Edit').first().click();
  await page1.getByRole('link', { name: 'Edit' }).first().click();
  await page1.getByRole('spinbutton').first().click();
  await page1.getByRole('spinbutton').first().fill('50');
  await page1.getByRole('spinbutton').nth(1).click();
  await page1.getByRole('spinbutton').nth(1).fill('30');
  await page1.getByRole('spinbutton').nth(2).click();
  await page1.getByRole('spinbutton').nth(2).fill('20');
  await page1.locator('#allowSpecificBrands1').nth(2).check();
  await page1.getByRole('button', { name: 'Save' }).first().click();
  await page1.getByRole('button', { name: 'Choose File' }).nth(1).click();
  await page1.getByRole('button', { name: 'Choose File' }).nth(1).setInputFiles('product_order_PSS04577-0029.pdf');
  await page1.getByRole('button', { name: 'Proceed' }).click();
  await page1.getByRole('link', { name: '+ Add Location' }).click();
  await page1.locator('label').filter({ hasText: 'Raigad' }).click();
  await page1.getByRole('checkbox', { name: 'Raigad Chittoor' }).check();
  await page1.getByRole('button', { name: 'Save' }).nth(1).click();
  await page1.getByRole('link', { name: 'Edit Seller List' }).click();
  await page1.getByRole('checkbox').nth(5).uncheck();
  await page1.getByRole('checkbox').nth(5).check();
  await page1.getByRole('button', { name: 'Save' }).nth(2).click();
  await page1.locator('div').filter({ hasText: /^\+ Add your choice of sellers$/ }).click();
  await page1.locator('.custom-control.custom-checkbox.seller-checkbox > .custom-control-label').first().click();
  await page1.getByText('+ Add your choice of sellers').click();
  await page1.locator('#knownSeller1').check();
  await page1.getByRole('button', { name: 'Save' }).nth(3).click();
  await page1.getByRole('button', { name: 'Submit Request' }).click();
  await page1.getByRole('button', { name: 'Cancel' }).click();
  await page1.getByText('RFQ status RFQ request submitted Sellers respond with prices Place an order').click();
  await page1.getByRole('button', { name: 'Track your RFQ' }).click();
  await page1.getByText('Audio Cables Quantity : 61').click();
  await page1.getByText('RFQ ID # RSS041231-').first().click();
  await page1.getByText('Placed on 27 Jan,').first().click();
  await page1.getByText('Quotations Received from0').first().click();
  await page1.getByText('RFQ expires in 6 Days').first().click();
  await page1.getByRole('button', { name: 'View RFQ Details' }).first().click();
});