import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(0);
  await page.goto('https://mssit3.lntsufin.com/');
  await page.getByRole('button', { name: 'track order Login' }).click();
  await page.getByRole('spinbutton').fill('44444444444');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.getByRole('dialog').locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  // await page.getByRole('button', { name: 'track orderHi, Buyer ' }).click();
  // await page.getByRole('button', { name: 'track orderHi, Buyer' }).click();
  // await page.getByRole('textbox', { name: 'Enter product name here...' }).click();
  // await page.getByRole('textbox', { name: 'Enter product name here...' }).fill('RSS041340-0013');
  // await page.getByRole('textbox', { name: 'Enter product name here...' }).press('Enter');
  // await page.getByRole('link', { name: 'Go Back' }).click();
  // await page.getByTitle('Request Quote for Bulk', { exact: true }).click();
  // await page.getByTitle('Request Quote for Bulk', { exact: true }).click();
  // await page.getByTitle('Request Quote for Bulk', { exact: true }).click();
   await page.getByRole('button', { name: 'track order Hi, Buyer' }).click();
  await page.getByRole('link', { name: 'Manage RFQs' }).click();
  await page.goto('https://mssit2.lntsufin.com/buyer/#/request-quote/manage/rfq-listing');
  // await page.getByRole('button', { name: 'track orderHi, Buyer ' }).click();
  // await page.getByRole('button', { name: 'track orderHi, Buyer' }).click();
  await page.getByRole('button', { name: 'View RFQ Details' }).first().click();
  await page.getByText('₹ 60,180.00 (inclusive of GST').click();
  await page.getByRole('button', { name: 'Accept Quote' }).click();
  await page.getByRole('button', { name: 'Place Order' }).click();
  await page.getByRole('button', { name: 'Change or Add Address' }).first().click();
  await page.getByLabel('', { exact: true }).check();
  await page.getByRole('button', { name: 'Deliver to this address' }).click();
  await page.getByRole('button', { name: 'Proceed to Payment' }).click();
  await page.getByRole('button', { name: 'Pay Now' }).click();
  await page.locator('#paymentStatus').selectOption('Success');
  await page.getByRole('button', { name: 'Pay' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Your Order Number is PSS04717-').click();
  await page.getByRole('button', { name: 'Order details' }).click();
 // await page.getByRole('button', { name: 'Order details' }).click();
  // await page.goto('https://mssit3.lntsufin.com/buyer/#/order/rfq-order-detail?orderId=PSS04717-0030&actionType=edit&readOnly=false');
});