import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(0);
  await page.goto('https://mssit2.lntsufin.com/');
  await page.getByRole('button', { name: 'track order Login' }).click();
  await page.getByRole('spinbutton').fill('44444444444');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.getByRole('dialog').locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'track order Hi, Buyer' }).click();
  await page.getByRole('link', { name: 'Manage RFQs' }).click();
  await page.goto('https://mssit2.lntsufin.com/buyer/#/request-quote/manage/rfq-listing');
  // await page.getByRole('button', { name: 'View RFQ Details' }).nth(1).click();
  // await page.goto('https://mssit2.lntsufin.com/buyer/#/request-quote/manage/rfq-listing');
  // await page.getByRole('button', { name: 'View RFQ Details' }).nth(4).click();
  // await page.getByRole('button', { name: 'Place Order' }).click();
  // await page.locator('#selectReturnItemsPopup').getByLabel('Close').click();
  // await page.getByRole('button', { name: 'View RFQ Details' }).first().click();
  await page.getByRole('button', { name: 'filters iconFilters' }).click();
  await page.getByText('Quotations Received', { exact: true }).click();
  await page.getByText('Last 30 days').click();
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('button', { name: 'View RFQ Details' }).nth(1).click();
  await page.getByRole('button', { name: 'Place Order' }).click();
  await page.getByRole('button', { name: 'Change or Add Address' }).first().click();
  await page.getByRole('button', { name: '+ Add New Address' }).click();
  await page.locator('#gstin-dropdown-btn').click();
  await page.locator('#dropdownlist').getByText('27BYONE1323Q1Z1').click();
  await page.getByRole('textbox', { name: 'Shop No, Gala No, Building' }).click();
  await page.getByRole('textbox', { name: 'Shop No, Gala No, Building' }).fill('');
  await page.getByRole('textbox', { name: 'Shop No, Gala No, Building' }).press('CapsLock');
  await page.getByRole('textbox', { name: 'Shop No, Gala No, Building' }).fill('XYZ');
  await page.getByRole('button', { name: 'Deliver to this address' }).click();
  await page.getByLabel('', { exact: true }).check();
  await page.getByRole('button', { name: 'Deliver to this address' }).click();
  await page.getByRole('button', { name: 'Proceed to Payment' }).click();
  await page.getByRole('button', { name: 'Confirm' }).click();
  await page.getByRole('button', { name: 'Pay Now' }).click();
  await page.locator('#paymentStatus').selectOption('Success');
  await page.getByRole('button', { name: 'Pay' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
});