import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://mssit2.lntsufin.com/shome');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('#mobileLoginNumber').click();
  await page.locator('#mobileLoginNumber').fill('1063123506');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.goto('https://mssit2.lntsufin.com/dashboard/#/seller/dashboard');
  await page.getByRole('button', { name: 'RFQs icon active RFQs' }).click();
  await page.goto('https://mssit2.lntsufin.com/seller/#/quote-response/manage/active-request?title=Manage%20your%20RFQs');
  await page.getByText('RFQ ID: RSS041231-0001 Expires in: 5 Days Audio Cables Quantity Required 61').click();
  await page.getByText('Buyer Buyer One mssit4 Ship to: Thane 400705 Payment Terms:50% On Order').click();
  await page.getByRole('button', { name: 'View Details' }).nth(1).click();
  await page.getByText('Cable Length :1.8 mtr Compatible Devices :All Connector :3.5 mm Mounting').click();
  await page.getByText('Quantity Required: 61 Piece(s)').first().click();
  await page.getByText('Expected Delivery Date: 06').first().click();
  await page.getByText('Ship To: Thane').first().click();
  await page.getByText('Payment Terms: 50% Pay on').first().click();
  await page.locator('.document-desp').first().click();
  await page.locator('#showDetails0').getByRole('img', { name: 'attach-file-icon' }).click();
  await page.getByText('Using Buyer\'s Specifications').click();
  await page.getByText('Product Specifications Cable').click();
  await page.locator('#collapse0').getByText('Rakesh', { exact: true }).click();
  await page.getByText('Quantity *Piece(s)').click();
  await page.getByRole('textbox').nth(1).fill('61');
  await page.getByText('Delivered Price *₹/ Per Piece').click();
  await page.getByRole('spinbutton').fill('1000');
  await page.getByText('GST *%').click();
  await page.locator('input[type="text"]').fill('18');
  await page.locator('div').filter({ hasText: /^Price Validity$/ }).nth(1).click();
  await page.locator('.input-group-text.ng-star-inserted').click();
  await page.getByText('31', { exact: true }).click();
  await page.getByText('Total Price(INR): 71,980.00 Payout for You Total Price ₹ 71,980.00 Commission (').click();
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('10');
  await page.getByText('+ Add Ex-works Price').click();
  await page.getByRole('textbox').nth(5).click();
  await page.getByRole('spinbutton').nth(1).click();
  await page.getByRole('spinbutton').nth(1).fill('1030');
  await page.getByText('GST %').click();
  await page.locator('input[type="text"]').nth(1).fill('14');
  await page.locator('#exPriceValidity').click();
  await page.getByText('Change or Add Address').click();
  await page.getByRole('button', { name: 'Select' }).click();
  await page.getByText('Select this address for all').click();
  await page.getByText('New Business Area Seller,').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(4).click();
  await page.locator('input[type="tel"]').nth(3).click();
  await page.locator('input[type="tel"]').nth(3).fill('10');
  await page.getByText('+ Upload Documents').click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04577-0029.pdf');
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Save Quote' }).click();
  await page.getByText('Using Your Catalogue').click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('1000');
  await page.locator('input[type="text"]').click();
  await page.locator('input[type="text"]').fill('10');
  await page.locator('base-datepicker svg').click();
  await page.getByText('31', { exact: true }).click();
  await page.getByRole('textbox').nth(4).click();
  await page.getByRole('textbox').nth(4).fill('10');
  await page.getByText('+ Add Ex-works Price').click();
  await page.getByRole('spinbutton').nth(1).click();
  await page.getByRole('spinbutton').nth(1).fill('1020');
  await page.locator('input[type="text"]').nth(1).click();
  await page.locator('input[type="text"]').nth(1).fill('10');
  await page.locator('svg').nth(2).click();
  await page.getByText('31', { exact: true }).click();
  await page.getByText('New Business Area Seller,').click();
  await page.locator('input[type="tel"]').nth(3).click();
  await page.locator('input[type="tel"]').nth(3).fill('10');
  await page.getByText('+ Upload Documents').click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04577-0029.pdf');
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Save Quote' }).click();
  await page.getByRole('button', { name: 'Submit Quotation' }).click();
  await page.getByRole('button', { name: 'Ok' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
});