import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(0);
  await page.goto('https://mssit3.lntsufin.com/shome');
  await page.getByRole('textbox', { name: 'Enter Your Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Mobile Number' }).fill('1063123506');
  await page.getByRole('button', { name: 'Get Started' }).click();
  await page.getByRole('button', { name: 'Get Started' }).click();
  await page.getByRole('button', { name: 'Get Started' }).click();
  await page.getByRole('button', { name: 'Get Started' }).click();
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'RFQs icon active RFQs' }).click();
  await page.goto('https://mssit3.lntsufin.com/seller/#/quote-response/manage/active-request?title=Manage%20your%20RFQs');
  await page.locator('.order-prod-image').first().click();
  await page.locator('.order-prod-image').first().click();
  await page.getByText('Buyer Rakesh SIT Four Buyer Ship to: Raigad 410210 Payment Terms:100% On Order').click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  await page.getByText('Safety Jackets Requirement').click();
  await page.getByText('Your Quote', { exact: true }).click();
  await page.locator('div').filter({ hasText: /^Using Buyer's Specifications$/ }).click();
  await page.locator('div').filter({ hasText: /^Using Your Catalogue Specifications$/ }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('20');
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('1000');
  await page.getByLabel('', { exact: true }).click();
  await page.locator('base-datepicker svg').click();
  await page.getByText('14', { exact: true }).click();
  await page.locator('#delPriceValidity').click();
  await page.getByText('Total Price(INR): 22,000.00 Payout for You Total Price ₹ 22,000.00 Commission (').click();
  await page.getByText('Time required to deliver shipment after receiving order *Days').click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button').nth(2).click();
  await page.getByRole('button').nth(2).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('tab', { name: 'Submitted (406)' }).click();
  await page.locator('#pills-pending-buyer > .row.mx-n2 > div > rfq-manage-qr-tab-content > .col-12.pl-0.pr-0.order-list > div').first().click();
  await page.getByRole('button', { name: 'View' }).first().click();
  await page.locator('.order-prod-tile').first().click();
  await page.getByText('15 Degree Elbows Requirement').click();
  await page.goto('https://mssit3.lntsufin.com/seller/#/quote-response/manage/active-request?orgId=OI3189-0000004&backFromTab=1');
  await page.getByRole('tab', { name: 'Expired (200)' }).click();
  await page.locator('.row.mx-0 > div > rfq-manage-qr-tab-content > .col-12.pl-0.pr-0.order-list > div').first().click();
  await page.getByRole('button', { name: 'View' }).first().click();
  await page.locator('.order-prod-tile').first().click();
  await page.locator('.order-prod-tile.quote-prod-tile').click();
  await page.getByRole('tab', { name: 'Expired (200)' }).click();
  await page.locator('.row.mx-0 > div > rfq-manage-qr-tab-content > .col-12.pl-0.pr-0.order-list > div:nth-child(3) > .order-prod-block > div > .col-12.col-lg-10 > .order-prod-desp-box > .order-prod-desp-sec > div > div > .order-prod-desp > .rfq-id-sec > .rfq-id-inner-sec').click();
  await page.locator('.row.mx-0 > div > rfq-manage-qr-tab-content > .col-12.pl-0.pr-0.order-list > div:nth-child(3)').click();
  await page.getByRole('button', { name: 'View' }).nth(2).click();
  await page.locator('.order-prod-desp-box').first().click();
  await page.getByText('Safety Jackets Requirement').click();
  await page.locator('.step-header-sec').first().click();
  await page.getByText('Using Buyer\'s SpecificationsUsing Your Catalogue Specifications').click();
  await page.locator('.select-best-match-box > .d-flex').click();
  await page.locator('.order-prod-img-box').click();
  await page.locator('.product-spec-box').click();
  await page.getByText('Step 2 Price Details').click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByText('Quantity *Piece(s)').click();
  await page.getByText('Delivered Price *₹/ Per Piece').click();
  await page.getByText('GST *%').click();
  await page.locator('div').filter({ hasText: /^Price Validity$/ }).nth(1).click();
  await page.getByText('Total Price(INR): 0.00 Payout').click();
  await page.getByText('Time required to deliver shipment after receiving order *Days').click();
  await page.getByRole('button', { name: 'Back' }).click();
  await page.getByRole('textbox', { name: 'Search' }).click();
  await page.getByRole('button', { name: 'filters iconFilters' }).click();
  await page.locator('div').filter({ hasText: /^Filter by$/ }).click();
  await page.locator('.card-header').first().click();
  await page.getByText('Days5 Days7 Days').click();
  await page.locator('.card.filter-by-card.ng-star-inserted > .card-header').click();
  await page.getByText('Delhi Rajasthan Daman And Diu').click();
  await page.getByRole('button', { name: 'Apply' }).click();
});