import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    test.setTimeout(0);
  await page.goto('https://mssit3.lntsufin.com/shome');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('#mobileLoginNumber').fill('1063123506');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'Orders icon active Orders' }).click();
  await page.getByRole('button', { name: 'Active (389)' }).click();
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).click();
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).fill('Audio Cables');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).fill('PSS04716-01313');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('Enter');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('ControlOrMeta+a');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).fill('Buyer One mssit4');
  await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('Enter');
  await page.getByRole('button', { name: 'filters icon Filters' }).click();
  await page.locator('#filterByOrderStatus').getByText('Payment Pending', { exact: true }).click();
  await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByText('View Specifications').first().click();
  await page.locator('.view-specifications-close').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('Buyer One mssit4').first().click();
  const page1 = await page1Promise;
  await page.getByRole('button', { name: 'View Details' }).first().click();
  await page.getByRole('button', { name: 'Manage Documents' }).click();
  await page.getByRole('img', { name: 'close icon' }).nth(2).click();
  await page.getByText('Download Documents').click();
  const downloadPromise = page.waitForEvent('download');
  await page.locator('a').filter({ hasText: /^Invoice$/ }).click();
  const download = await downloadPromise;
  await page.getByRole('img', { name: 'close icon' }).click();
});