import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(0);
  await page.goto('https://mssit3.lntsufin.com/shome');
  await page.getByRole('textbox', { name: 'Enter Your Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Mobile Number' }).fill('1063123506');
  await page.getByRole('button', { name: 'Get Started' }).click();
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'Orders icon active Orders' }).click();
  await page.goto('https://mssit3.lntsufin.com/seller/#/productOrders/active-orders?title=Manage%20Product%20Orders');
  await page.getByRole('heading', { name: 'My Orders' }).click();
  await page.getByRole('button', { name: 'Pending (16)' }).click();
  await page.locator('.order-info-section').first().click();
  await page.getByText('Please confirm payment received from the buyer. Safety Jackets View').click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  await page.locator('.card-header-box').click();
  await page.locator('.purchased-item-tile').click();
  await page.locator('.row.mx-0.ship-to-pickup-addr-section').click();
  await page.getByText('Payment DetailsPaymentAmountPaid By Buyer to You ( verify this amount)₹').click();
  await page.getByTitle('PVC Yellow Fusion Safety').click();
  await page.getByText('Quantity: 15 Piece(s)').click();
  await page.locator('#shipmentDetails1').getByText('₹').click();
  await page.getByText('Pickup From: Rakesh SIT Four SellerEditNew Business Area SellerElectronic Zone').click();
  await page.getByText('Payment Details', { exact: true }).click();
  await page.getByText('PaymentAmount').click();
  await page.getByText('Paid By Buyer to You ( verify this amount)₹').click();
  await page.getByText('Payment Proof by Buyer').click();
  await page.getByText('SupportingDoc1111111111311.pdf').click();
  await page.getByText('Note : SuFin will process the').click();
  await page.getByText('I have received ₹3,750.00').click();
  await page.getByRole('button', { name: 'Reject' }).click();
  await page.getByRole('heading', { name: 'Reject Payment Proof' }).click();
  await page.getByText('Please provide a reason for').click();
  await page.getByRole('textbox', { name: 'Enter Reason for Rejection' }).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
  await page.getByText('Order Info Payment').click();
  await page.getByText('Invoice Details').first().click();
  await page.getByText('Invoice No.').first().click();
  await page.getByText('Invoice No. invoice008').first().click();
  await page.getByText('Invoice Date 01 Jan,').click();
  await page.getByText('Invoice Value ₹18750').click();
  await page.getByText('Expected Payout ₹').click();
  await page.getByText('Buyer Swanya').click();
  await page.getByText('Documents From Buyer').click();
  await page.locator('div').filter({ hasText: /^invoice-invoice008-rakesh-swanya\.pdf$/ }).first().click();
  await page.locator('.need-help-section').click();
  await page.getByText('Need Help ?').click();
  await page.getByText('+91 8291 211 421(Mon-Fri, 9:').click();
  await page.getByText('orb2bhelp@larsentoubro.com').click();
  await page.locator('.left-container').click();
  await page.goto('https://mssit3.lntsufin.com/seller/#/productOrders/active-orders?title=Manage%20Product%20Orders');
  await page.getByRole('button', { name: 'Active (424)' }).click();
  await page.getByText('Order ID # PSS04557-0006Placed on 24 Dec,').click();
  await page.getByText('Order Value₹ 2,360.00').click();
  await page.getByText('Buyer Rakesh SIT Four Buyer').nth(1).click();
  await page.getByText('Order Status : In Progress').nth(2).click();
  await page.getByText('You have pending task(s) in').nth(3).click();
  await page.locator('div:nth-child(4) > .col-12 > .order-items-tile > .purchased-item-tile > .purchased-item-block > .item-desp-section > .item-desp-block > .item-desp-inner-block > .item-desp-box > .purchased-item-image').click();
  await page.getByRole('heading', { name: 'Bitumen' }).nth(1).click();
  await page.getByText('View Specifications').nth(3).click();
  await page.getByText('Bitumen Quantity: 2 Piece(s)').click();
  await page.getByText('Brand Smart').click();
  await page.getByText('Requirement Details Pack Size').click();
  await page.locator('.view-specifications-close').click();
  await page.getByText('Quantity 50 Piece(s)').nth(3).click();
  await page.getByText('Item Value₹ 2,360.00').nth(1).click();
  await page.getByRole('button', { name: 'View Details' }).nth(3).click();
  await page.getByText('Shipment 1 : Ready For').click();
  await page.locator('#mat-dialog-0').getByText('Update Details').click();
  await page.locator('div').filter({ hasText: /^Dispatch Date \*$/ }).nth(3).click();
  await page.locator('.ng-star-inserted > .modal-dialog-centered > .modal-content > .modal-body > .update-details-section > .update-details-form > div > .col-12.col-lg-6.pl-0.pl-lg-2 > .form-group').first().click();
  await page.locator('#mat-dialog-0').getByText('Tracking Number').click();
  await page.locator('#mat-dialog-0 #trackingNumber').click();
  await page.locator('#mat-dialog-0').getByText('Tracking URL').click();
  await page.locator('#mat-dialog-0 #trackingUrl').click();
  await page.getByRole('button').filter({ hasText: /^$/ }).click();
  await page.getByText('Deliver By 13 Jan, 2026 Track').first().click();
  await page.getByRole('button', { name: 'Manage Documents' }).first().click();
  await page.locator('div').filter({ hasText: /^Tax InvoiceInvoice\.jpgInvoice No:INV0031Invoice Date:11 Jan 2026$/ }).first().click();
  await page.locator('div').filter({ hasText: /^E-way Bill$/ }).first().click();
  await page.locator('div').filter({ hasText: /^LR Copy$/ }).first().click();
  await page.locator('div').filter({ hasText: /^POD$/ }).first().click();
  await page.locator('div').filter({ hasText: /^Advance Shipping Note$/ }).first().click();
  await page.getByRole('img', { name: 'close icon' }).nth(2).click();
  await page.locator('.purchased-item-image').first().click();
  await page.getByText('Bitumen View').first().click();
  await page.locator('div').filter({ hasText: /^Quantity: 2 Piece\(s\) ₹ 94\.40$/ }).nth(1).click();
  await page.getByText('Order InfoOrder Status : In').click();
  await page.getByText('Order ID # PSS04557-0006 Placed on 24 Dec,').click();
  await page.getByText('RFQ ID RSS041219-').click();
  await page.getByText('Delivery Mode Shipped by').click();
  await page.getByText('Buyer\'s Payment Terms Paid 100% On Order Placement').click();
  await page.getByText('Bill To: Rakesh SIT Four BuyerRakesh Shinde, New Business Area, Electronic Zone').click();
  await page.getByText('Payment Summary Order Amount₹').click();
  await page.goto('https://mssit3.lntsufin.com/seller/#/productOrders/active-orders?title=Manage%20Product%20Orders');
  await page.getByRole('button', { name: 'Completed (48)' }).click();
  await page.getByText('Order ID # PSS04573-0009Placed on 08 Jan,').click();
  await page.getByText('Order Value₹').first().click();
  await page.getByText('Buyer Swanya').first().click();
  await page.getByText('Order Status : Completed').first().click();
  await page.locator('.purchased-item-image').first().click();
  await page.getByText('Safety Jackets View').first().click();
  await page.getByRole('img', { name: 'close icon' }).nth(1).click();
  await page.getByText('Quantity 15 Piece(s)').nth(1).click();
  await page.getByText('Item Value₹').nth(1).click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  await page.getByText('Shipment : Delivered').click();
  await page.getByText('Picked Up On 08 Jan,').click();
  await page.getByText('Track Shipment').click();
  await page.getByRole('heading', { name: 'Shipping Details' }).click();
  await page.locator('.shipping-info-box').click();
  await page.getByText('Ready for Dispatch', { exact: true }).click();
  await page.locator('div').filter({ hasText: /^Ready for Dispatch$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Picked Up$/ }).nth(1).click();
  await page.locator('div').filter({ hasText: /^Pickup Confirmed08 Jan 2026$/ }).nth(1).click();
  await page.getByText('Pickup From: Rakesh SIT Four SellerNew Business Area SellerElectronic Zone').click();
  await page.getByRole('img', { name: 'close icon' }).nth(1).click();
  await page.getByRole('button', { name: 'Manage Documents' }).click();
  await page.locator('div').filter({ hasText: /^Tax InvoiceInvoice\.pdfInvoice No:vishu2Invoice Date:01 Jan 2026$/ }).first().click();
  await page.locator('div').filter({ hasText: /^E-way BillE-WayBill\.pdf$/ }).first().click();
  await page.locator('#shipmentDetails1').getByText('Advance Shipping Note').click();
  await page.getByRole('img', { name: 'close icon' }).nth(2).click();
  await page.getByTitle('PVC Yellow Fusion Safety').click();
  await page.getByText('Quantity: 15 Piece(s)').click();
  await page.getByText('Quantity: 15 Piece(s)').click();
  await page.getByText('Order Status : Completed').click();
  await page.getByText('Order ID # PSS04573-0009 Placed on 06 Jan,').click();
  await page.getByText('Delivery Mode Pickup by Buyer').click();
  await page.getByText('Buyer\'s Payment Terms Paid 100% On Order Placement').click();
  await page.getByText('Bill To: SwanyaInfinity').click();
  await page.getByRole('heading', { name: 'Payment Summary' }).click();
  await page.getByText('Order Amount₹').click();
  await page.getByText('Deductions₹').click();
  await page.getByText('Expected Payment₹').click();
  await page.goto('https://mssit3.lntsufin.com/seller/#/productOrders/active-orders?title=Manage%20Product%20Orders');
  await page.getByRole('button', { name: 'Cancelled & Rejected (11)' }).click();
  await page.getByText('Order ID # PSS04570-0005Placed on 05 Jan,').click();
  await page.getByText('Order Value₹').first().click();
  await page.getByText('Buyer Buyer One mssit4').first().click();
  await page.getByText('Order Status : Payment').first().click();
  await page.getByRole('heading', { name: 'Safety Jackets' }).first().click();
  await page.getByText('Quantity 100 Piece(s)').nth(1).click();
  await page.getByText('Item Value₹').nth(1).click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  await page.getByRole('heading', { name: 'Item(s) in this order' }).click();
  await page.getByTitle('PVC Yellow Fusion Safety').click();
  await page.getByText('Quantity: 100 Piece(s)').click();
  await page.locator('#shipmentDetails1').getByText('₹').click();
  await page.getByText('Pickup From: Rakesh SIT Four SellerEditNew Business Area SellerElectronic Zone').click();
  await page.getByText('Order Info Payment').click();
  await page.getByText('Invoice DetailsInvoice No.').click();
  await page.getByText('Payment DetailsPaymentAmountPaid By Buyer to You ( rejected by you)₹').click();
  await page.goto('https://mssit3.lntsufin.com/seller/#/productOrders/active-orders?title=Manage%20Product%20Orders');
  await page.getByRole('button', { name: 'profile Hello, Rakesh Rakesh' }).click();
  await page.locator('a').filter({ hasText: 'Logout' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.goto('https://mssit3.lntsufin.com/shome');
});