import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    test.setTimeout(0);

  await page.goto('https://mssit3.lntsufin.com/shome');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('#mobileLoginNumber').fill('1');
  await page.locator('#mobileLoginNumber').click();
  await page.locator('#mobileLoginNumber').fill('1063123506');
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'Orders icon active Orders' }).click();
  await page.goto('https://mssit3.lntsufin.com/seller/#/productOrders/active-orders?title=Manage%20Product%20Orders');

//   await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).click();
//   await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).fill('RSS041340-0003');
//   await page.getByRole('textbox', { name: 'Search by Order ID, Product' }).press('Enter');
  await page.getByRole('button', { name: 'filters icon Filters' }).click();
  await page.getByText('Last 3 Months').click();
  await page.getByText('Order Confirmed').click();
await page.getByRole('button', { name: 'Apply' }).click();
 //await page.getByRole('button', { name: 'View Details' }).first().click();
 //await page.getByRole('button', { name: 'Active (1155)' }).click();
 //await page.getByRole('button', { name: 'View Details' }).first().click();
// await page.getByRole('button', { name: 'Apply' }).click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  await page.getByRole('checkbox').nth(1).check();
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('Click Here').click();
  const page1 = await page1Promise;
  await page.getByRole('button', { name: 'Prepare for Dispatch' }).click();
  await page.getByText('L&T-SuFin Logistics', { exact: true }).click();
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('button', { name: 'Upload' }).first().click();
  await page.getByRole('textbox', { name: 'Invoice Number *' }).click();
  await page.getByRole('textbox', { name: 'Invoice Number *' }).fill('3333');
  await page.getByLabel('', { exact: true }).click();
  await page.locator('#mat-dialog-0 path').click();
  await page.getByText('2', { exact: true }).click();
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04577-0029.pdf');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Upload' }).click();
  await page.getByRole('textbox', { name: 'E-Way Bill Number *' }).click();
  await page.getByRole('textbox', { name: 'E-Way Bill Number *' }).fill('55');
  await page.getByRole('button', { name: 'Choose File' }).click();
  await page.getByRole('button', { name: 'Choose File' }).setInputFiles('product_order_PSS04577-0029.pdf');
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByRole('img').nth(5).click();
  await page.getByText('4', { exact: true }).click();
  await page.locator('path').nth(2).click();
  await page.getByText('4', { exact: true }).click();
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.locator('#FTL').check();
  await page.locator('#truckType').selectOption('1');
  await page.getByRole('textbox', { name: 'Enter here' }).click();
  await page.getByRole('textbox', { name: 'Enter here' }).fill('4');
  await page.getByRole('button', { name: 'Save & Next' }).click();
  await page.getByRole('button', { name: 'Get Quote' }).click();
  await page.getByRole('button', { name: 'OK' }).click();
  await page.getByText('Download Documents').click();
  const downloadPromise = page.waitForEvent('download');
  await page.locator('a').filter({ hasText: /^Invoice$/ }).nth(1).click();
  const download = await downloadPromise;
  const download1Promise = page.waitForEvent('download');
  await page.locator('a').filter({ hasText: 'E-Way Bill' }).nth(1).click();
  const download1 = await download1Promise;
  await page.getByRole('img', { name: 'close icon' }).click();
  await page.locator('.cdk-overlay-backdrop').click();
  await page.getByRole('button', { name: 'Manage Documents' }).click();
  await page.getByRole('img', { name: 'close icon' }).nth(2).click();
  await page.getByText('Track Shipment').click();
  await page.getByRole('img', { name: 'close icon' }).nth(1).click();
  await page.getByText('View Specifications').first().click();
  await page.getByRole('img', { name: 'close icon' }).first().click();
});