import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  test.setTimeout(0);
  await page.goto('https://mssit3.lntsufin.com/shome');
  await page.getByRole('textbox', { name: 'Enter Your Mobile Number' }).click();
  await page.getByRole('textbox', { name: 'Enter Your Mobile Number' }).fill('1063123506');
  await page.getByRole('button', { name: 'Get Started' }).click();
  await page.getByRole('button', { name: 'Get OTP' }).click();
  await page.locator('#otpInput').click();
  await page.locator('#otpInput').fill('2');
  await page.locator('#otpInput').press('ArrowRight');
  await page.locator('#otpInput').fill('1234');
  await page.getByRole('button', { name: 'Verify' }).click();
  await page.getByRole('button', { name: 'Catalogue icon active' }).click();
  await page.locator('micro-seller-side-menu').getByText('View Catalogue').click();
  await page.getByRole('button', { name: 'Add SKU' }).click();
  await page.locator('micro-seller-side-menu').getByRole('button', { name: 'Catalogue icon active' }).click();
  await page.getByRole('button', { name: 'Active Requests' }).click();
  await page.getByRole('tab', { name: 'Single SKU History' }).click();
  await page.getByRole('tab', { name: 'Bulk SKU Requests' }).click();
  await page.getByRole('tab', { name: 'Bulk SKU History' }).click();
  await page.locator('micro-seller-side-menu').getByRole('button', { name: 'Administer Request' }).click();
  await page.getByRole('tab', { name: 'Bulk SKU Requests' }).click();
  await page.locator('micro-seller-side-menu').getByRole('button', { name: 'Suggest a Product' }).click();
  await page.getByRole('button', { name: 'Add Suggestion' }).click();
  await page.getByLabel('Category *', { exact: true }).selectOption('10167');
  await page.locator('micro-seller-side-menu').getByRole('button', { name: 'SKU Bulk Update' }).click();
  await page.getByRole('listitem').filter({ hasText: 'Pricing' }).nth(3).click();
  await page.getByRole('button', { name: 'Product Serviceability' }).click();
  await page.locator('#gstin-dropdown-btn').first().click();
  await page.getByRole('button', { name: 'Orders icon active Orders' }).click();
  await page.goto('https://mssit3.lntsufin.com/seller/#/productOrders/active-orders?title=Manage%20Product%20Orders');
  await page.getByRole('button', { name: 'Active (424)' }).click();
  await page.getByRole('button', { name: 'Completed (48)' }).click();
  await page.getByRole('button', { name: 'Cancelled & Rejected (11)' }).click();
  await page.getByRole('button', { name: 'Pending (15)' }).click();
  await page.getByRole('button', { name: 'View Details' }).first().click();
  await page.goto('https://mssit3.lntsufin.com/catalogue/#/seller/product-serviceability?tab=0');
  await page.getByRole('button', { name: 'RFQs icon active RFQs' }).click();
  await page.locator('div').filter({ hasText: /^View Details$/ }).nth(1).click();
  await page.getByText('Piece(s)', { exact: true }).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('spinbutton').click();
  await page.locator('#collapse0 input[type="text"]').click();
  await page.getByLabel('', { exact: true }).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button').nth(3).click();
  await page.getByRole('button', { name: 'Cancel' }).click();
});